### ISSUE TITLE
Linux script issues

### ISSUE THREAD

**Issue by Inovvia** [cheatfreak47/NMSDecompressinator#3]
Unfortunately there are some issues with missing textures and crashes. I'll try to find some fixes for this and maybe someone else can too.

**Comment by Inovvia** [comment]
I saw this issue looking for path / filename issues for psarc - https://github.com/periander/PSArcTool/issues/1

**Comment by cheatfreak47** [comment]
so it seems psarc itself has problems then?

**Comment by Inovvia** [comment]
Not quite sure yet, I'm experimenting with different solutions. I tried using a uncompressed version using my windows and there was no crashes. Hopefully I or someone else can fix this.

**Comment by cheatfreak47** [comment]
Oh, the issue you referenced shouldn't be related, that seems to be windows permissions issues stuff

**Comment by cheatfreak47** [comment]
looking through it also seems all the code related to moving the files into a backup folder is missing too, there's obviously some problems with this currently so but a wip linux script is better than none so I'll just leave it as is, if someone wants to come fix it with a PR, by all means

**Comment by Inovvia** [comment]
After several hours of trial and error.  the script works fine IF you put it on a sane folder name / path

What i did was create a folder from my home called "NMS" and ran the script then copied the repacked files from that location. I'll check further how to handle the apostrophe which probably causing issues since the folder is named "No Man's Sky" and create a PR if I manage to handle it.

**Comment by cheatfreak47** [comment]
any progress on figuring out how to make this work properly on Linux?

**Comment by Inovvia** [comment]
I'll try again later. I was playing too much during the weekend 🤣
